name: Stage the app

# Controls when the workflow will run
on:
  pull_request:
    types: [labeled]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build: 
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')
    
